{
 "title": "Netzbremse",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_download [1m]))"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_upload [1m]))"
    }
   ]
  },
  {
   "title": "Download Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_downLoadedJitter [1m]))"
    }
   ]
  },
  {
   "title": "Upload Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_upLoadedJitter [1m]))"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_downLoadedLatency [1m]))"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(endpoint) (sum_over_time({job=\"$job\"} |= `` | json | unwrap result_upLoadedLatency [1m]))"
    }
   ]
  }
 ]
}